version: '3.8'
services:
    mysql:
      image: mysql:8.0
      container_name: user-management
      restart: no
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: user-management-db
        MYSQL_USER: user
        MYSQL_PASSWORD: root
      ports:
        - 3306:3306
      volumes:
        - user_management_db_data:/mysql/data:/var/lib/mysql
volumes:
  user_management_db_data: